### ISSUE TITLE
Remove dead projects

### ISSUE THREAD

**Issue by JakeDevs** [modrinth/awesome#21]
### Is your suggested enhancement related to a problem? Please describe.

It is a pain to sort through the dead projects to find the ones that are still being maintained.

### Describe the solution you'd like

A good solution would be to simply remove them.

### Describe alternatives you've considered

If removing them is too nuclear, an unmaintained section is another idea. Projects could be added back if they are maintained once again.

**Comment by triphora** [comment]
Please submit a pull request if you find any dead projects, it's not really feasible for us to go through every single one on the list and decide whether it's maintained or not
